name: 'TurboGHA - Caching for Turborepo'
description: 'Fast Turborepo Remote Caching for GitHub Actions. Free, self-hosted, no Vercel needed.'
author: 'artik0din'

branding:
  icon: 'zap'
  color: 'blue'

inputs:
  cache-prefix:
    description: 'Prefix for the cache key'
    required: false
    default: turbogha_
  server-port:
    description: 'Port for the caching server'
    required: false
    default: '41230'

runs:
  using: node20
  main: dist/setup/index.js
  post: dist/post/index.js
